# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green)'

[time]
disabled = false

[status]
disabled = false

[gcloud]
disabled = true

[aws]
disabled = true

[python]
disabled = true
