add_newline = false

[line_break]
disabled = true

[username]
show_always = true
format = '[$user]($style)@'

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style) '

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green)'

[time]
disabled = true
time_format = '%H:%M %p'

[cmd_duration]
disabled = true

[status]
disabled = false

[gcloud]
disabled = true

[aws]
disabled = true

[python]
disabled = true
